### ISSUE TITLE
Support Python2.x

### ISSUE THREAD

**Issue by Hironsan** [chakki-works/chazutsu#3]
I could successfully install chazutsu in python2.7.10.
But there is a problem.

when I import chazutsu, I have a following issue:
```python
>>> import chazutsu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/VirtualEnv/py2venv/lib/python2.7/site-packages/chazutsu/__init__.py", line 1, in <module>
    import chazutsu.datasets as datasets
  File "/Users/xxx/VirtualEnv/py2venv/lib/python2.7/site-packages/chazutsu/datasets/__init__.py", line 1, in <module>
    from .movie_review import MovieReview
  File "/Users/xxx/VirtualEnv/py2venv/lib/python2.7/site-packages/chazutsu/datasets/movie_review.py", line 5, in <module>
    from chazutsu.datasets.framework.dataset import Dataset
  File "/Users/xxx/VirtualEnv/py2venv/lib/python2.7/site-packages/chazutsu/datasets/framework/dataset.py", line 10, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
```

Maybe, it's due to the specification change of urllib between python2.x and python3.x.

**Comment by icoxfog417** [comment]
## [Using python2?](https://github.com/BayesianFreaks/scikit-stan)

> Are you joking?
> 
> We can't touch you because we are living in the future from you, and you're living in past ages. Please 
> say hello to Nobunaga Oda.
> 
> We will always use newest features of the latest version of python, so you should use the latest version 
> of python.
